#!/usr/bin/env php
<?php

/**
 * Serfer
 * Episode/Series filename re-namer and information lookup script
 *
 * @author Rob Frawley
 * @copyright 2009 Inserrat LLC.
 * @license MIT License
 * @version $Id$
 */

/*
 * filename skeleton used as template for episode renaming with obtained 
 * episode information
 */
$_runtime['skeleton']['filename'] = 
  '${seriesname} S{episodeseason}E${episodenumber} ${episodename}';

/**
 * search skeleton used to search epguides for the series name derived from 
 * the current working directory name or input by the user
 */
$_runtime['skeleton']['onlinesearch'] = 
  'http://epguides.com/${seriesname}/';

/**
 * resource handle to standard output (stdout), commonly used in the wrapper
 * comands echo and print. acted upon as if it is a file, for example, used 
 * with fwrite
 */
$_runtime['handle']['stdout'] = fopen('php://stdout', 'w');


/**
 * output text to console, by default no trailing newline
 *
 * @param $to_output string text to output to console
 * @param $trailing_nl boolean should text have trailing newline afterwards
 * @return boolean
 */
function out($to_output = '', $trailing_nl = false)
{
  global $_runtime;
  
  if($trailing_nl === true)
  {
    $to_output .= "\n";
  }
  
  $return = @fwrite($_runtime['handle']['stdout'], $to_output);
  
  return (boolean) ($return === false ? false : true);
}

/**
 * output line of text to console, trailing newline always
 *
 * @param $to_output string text to output to console
 * @return boolean
 */
function out_l($to_output = '')
{
  return (boolean) out($to_output, true);
}

/**
 * output program start information to console
 *
 * @return boolean
 */
function out_proginfo()
{
  out_l('Serfer (Version 0.1.0)');
  out_l('<http://robfrawley.com/projects/serfer>');
  out_l();
  out_l('Written by Rob Frawley <projects@robfrawley.com>');
  out_l('Copyright 2009 Inserrat LLC <http://inserrat.com>');
  out_l('Licensed under the MIT License');
  out_l();
  
  return (boolean) true;
}

/**
 * main function handles the script from beginning to end
 */
function main()
{
  /* bring config variable array, defined and available outside this
     function's scope, into focus inside this function */
  global $_runtime;

  /* display program name/version/license information */
  out_proginfo();

}

/* run main script function: go */
main();

?>